server:
  port: 9056
  servlet:
    session:
      timeout: 60s # 테스트를 위해 세션 시간을 짧게 잡는다.

spring:

  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    check-template-location: true

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:file:~/dev/temp/h2db/rememberme; # File DB를 사용하도록 지정
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update # File DB를 사용하기 위해 update로 설정
